apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: prometheus-monitoring-system
  labels:
    app: node-exporter
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  selector:
    app: node-exporter
    